version: '3'
services:
  nodejs:
    container_name: nodejs
    build:
      context: ./dockerfiles/nodejs
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - ./app:/usr/src/app
    tty: true
    stdin_open: true